DROP TABLE if EXISTS users;
	CREATE TABLE users (
		id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
		username TEXT NOT NULL,
		hash TEXT NOT NULL
);

DROP TABLE if EXISTS posts;
	CREATE TABLE posts (
		id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
		name TEXT NOT NULL,
		content TEXT NOT NULL
);

DROP TABLE if EXISTS followers;
	CREATE TABLE followers (
		id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
		user TEXT NOT NULL,
		following TEXT NOT NULL
	);